version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter"
        versions: ["2.5.0"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"