##############################
### profile settings access, can be overwritten when running the application jar,
###    java -jar -Dspring.profiles.active=docker
##############################
spring:
  profiles:
    active: development,authenticate,ingredient,notification,recipe,user,user_ingredient
  config:
    import: optional:file:.env[.properties]


---
##############################
### Application common settings
##############################
server:
  port: 8089
##############################
### database access
##############################
spring:
  application:
    name: backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl: none
    show-sql: true
##############################
### logging access
##############################
logging:
  file:
    name: logs/backend.log
  level:
    nus:
      iss:
        team3:
          backend: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
##############################
### individual environment setup
##############################
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://${POSTGRES_LOCAL_IP}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_DOCKER_IP}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
##############################
### DigitalOcean environment setup
##############################
spring:
  config:
    activate:
      on-profile: k8test
  datasource:
    url: jdbc:postgresql://${POSTGRES_K8_TEST_IP}:${POSTGRES_K8_TEST_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_K8_TEST_USER}
    password: ${POSTGRES_K8_TEST_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: k8prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_K8_PROD_IP}:${POSTGRES_K8_PROD_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_K8_PROD_USER}
    password: ${POSTGRES_K8_PROD_PASSWORD}

### to look at https://www.geeksforgeeks.org/spring-boot-application-properties/ for database connection
