name: fEATs backend

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - uses: thecodemonkey/action-get-gradle-version@master
        id: version

      - name: Build Docker container with 'latest' tag
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/feats-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image (latest) to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-backend:latest

      - name: Push Docker image (version) to Docker Hub
        run: |
          VERSION=$(echo "${{ steps.version.outputs.version }}" | sed "s/^['\"]\(.*\)['\"]$/\1/")
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/feats-backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/feats-backend:$VERSION
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-backend:$VERSION