name: fEATs backend

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlesscheck

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - uses: thecodemonkey/action-get-gradle-version@master
        id: version

      - name: Build Docker container with 'latest' tag
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}/feats-backend:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push Docker image (latest) to DigitalOcean Container Registry
        run: |
          docker push ${{ secrets.REGISTRY_NAME }}/feats-backend:latest

      - name: Push Docker image (version) to DigitalOcean Container Registry
        run: |
          VERSION=$(echo "${{ steps.version.outputs.version }}" | sed "s/^['\"]\(.*\)['\"]$/\1/")
          docker tag ${{ secrets.REGISTRY_NAME }}/feats-backend:latest ${{ secrets.REGISTRY_NAME }}/feats-backend:$VERSION
          docker push ${{ secrets.REGISTRY_NAME }}/feats-backend:$VERSION