name: SAST Scan with Synk

on:
  workflow_dispatch: # manual trigger

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21] # Use a stable and supported Java version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}